#import "main-defs.typ": *
#import "statements.typ": *

#chapter[Review of Results on Algebraic Groups] <ch:algebraic-groups>

#source(11)
The references for this chapter are @bib:Borel1969, @bib:Hartshorne1977, and
@bib:Humphreys1975. We will define affine varieties, introduce linear algebraic
groups over an algebraically closed field, and review some of their basic
properties.

We will mostly follow the notation of @bib:Humphreys1975. Let $K$ be an
algebraically closed field. An _affine variety_ $X subset K^n$ is the set of
zeros in $K^n$ of a (finite) set of polynomials in $K[x_1, x_2, dots, x_n]$. The
Zariski topology on $K^n$ is defined by stipulating that the closed sets are
affine varieties. Then we have the induced Zariski topology on any subset $X$ of
$K^n$.

An affine variety $X$ is said to be _irreducible_ if $X$ is not the union of two
proper non-empty closed subsets. Any affine variety can be written as the union
of a finite number of closed irreducible subsets called its components. If $I$
is the ideal of all polynomials in $K[x_1, x_2, dots, x_n]$ which vanish on the
affine variety $X$, $X$ is irreducible if and only if $I$ is a prime ideal. The
ring $K[X] = K[x_1, x_2, dots, x_n] / I$ is called the _affine coordinate ring_
of $X$. Each element $f + I in K[X]$ (where $f in K[x_1, x_2, dots, x_n]$) gives
rise to a $K$-valued function on $X$; if $(a_1, a_2, dots, a_n) in X$, we map it
on $f(a_1, a_2, dots, a_n) in K$. So $K[X]$ is also called the algebra of
polynomial functions on $X$. It is a finitely generated $K$-algebra, and $X$ can
be identified with $op("Hom")_(K)(K[X], K)$. If $X$ is irreducible, the
_dimension_ of $X$ is the transcendence degree of the quotient field $K(X)$ of
$K[X]$, #source(12) over $K$.

Let $X subset K^n$, $Y subset K^m$ be affine varieties. We say a map
$phi: X -> Y$ is a _morphism_ if
$phi(a_1, a_2, dots, a_n) =
(psi_(1)(a_1, a_2, dots, a_n), dots, psi_(m)(a_1, a_2, dots, a_n))$
where $psi_1, dots, psi_m in K[x_1, x_2, dots, x_n]$. The morphism $phi$ induces
a _comorphism_ $phi^*: K[Y] -> K[X]$ by $phi^(*)(f) = phi dot f$ and $phi^*$ is
a $K$-algebra homomorphism. If $X, Y$ are affine varieties, we can define a
product variety $X times Y$ and $K[X times Y] tilde.eq K[X] ⊗ K[Y]$.

We can define the Zariski topology on projective $n$-space $bb(P)^n$ over $K$ by
taking closed sets to be the common zeros of a set of homogeneous polynomials
over $K$. The closed subsets of $bb(P)^n$ are called projective varieties. A
_quasi-projective_ variety is an open set in a projective variety.

We regard $upright("GL")(n, K)$, the group of all $n times n$ invertible
matrices over $K$, as being embedded in $K^(n^2)$. Then a group
$G subset upright("GL")(n, K)$ is called a linear algebraic group if it is the
intersection with $upright("GL")(n, K)$ of a closed subset of $K^(n^2)$. A map
$G -> H$ of _linear algebraic groups_ is a morphism if it is a morphism in the
sense of affine varieties and a group homomorphism.

_Examples of linear algebraic groups._

+ $upright("GL")(n, K)$.
+ $upright("SL")(n, K)$, the group of $n times n$ matrices with determinant 1
  over $K$.
+ $upright("Sp")(2n, K) = {A in upright("GL")(2n, K) |
    attach(A, tl: t) mat(0, J; -J, 0) A = mat(0, J; -J, 0)}$, where $J$ is the
  $n times n$ matrix $mat(, , 1; , dots.up, ; 1, ,)$.
  #source(13)
+ $upright("O")(2n + 1, K) = {A in upright("GL")(2n + 1, K) |
    attach(A, tl: t) mat(1, 0, 0; 0, 0, J; 0, J, 0) A =
    mat(1, 0, 0; 0, 0, J; 0, J, 0)}$ where $op("char") K != 2$.

  $upright("SO")(2n + 1, K) =
  upright("O")(2n + 1, K) ∩ upright("SL")(2n + 1, K)$.
+ $upright("O")(2n, K) = {A in upright("GL")(2n, K) |
    attach(A, tl: t) mat(0, J; J, 0) A = mat(0, J; J, 0)}$
  where $op("char") K != 2$.

  $upright("SO")(2n, K) =
  upright("O")(2n, K) ∩ upright("SL")(2n, K)$.

  #remark[
    The groups of 4 and 5 have to be defined differently in characteristic 2.
    See @bib:Carter1972, p.~8.
  ]
+ The group of diagonal matrices over $K$.
+ The group of upper triangular matrices over $K$.
+ The group of upper triangular matrices over $K$ with entries 1 along the
  diagonal.
+ $G_2(K)$: A group of type $G_2$ over $CC$ can be defined as the group of
  automorphisms of a Cayley algebra. In analogy with this, we can define a group
  $G_2(K)$ over $K$ to be generated by $7 times 7$ matrices over $K$ satisfying
  certain conditions (see e.g.~@bib:Ree1957, p.~400).

Let $G$ be a linear algebraic group. Then there is a unique irreducible
component $G^0$ of $G$ containing the identity element, and $G^0$ is a normal
subgroup of finite index. $G$ is connected (in the Zariski topology) if and only
if $G$ is irreducible, and if and only if $G$ has no proper closed subgroup of
finite index. (See @bib:Humphreys1975, 7.3.)

#source(14)
#example[
  $upright("O")(2n, K)$ is not connected, whereas $upright("SL")(2n, K)$ is
  connected.
]

_Definitions._

+ $G$ is simple if it has no proper closed connected non-trivial normal
  subgroups.

  #example[$upright("SL")(n, K)$.]
+ $G$ is _semisimple_#term-entry("Semisimple group") if it has no closed
  connected non-trivial normal abelian subgroups.

  _Examples._ $upright("SL")(n, K)$, $upright("Sp")(2n, K)$,
  $upright("SO")(2n + 1, K)$, $upright("SO")(2n, K)$.
+ $G$ is _unipotent_ if it is isomorphic to a closed subgroup of the group of
  upper triangular $n times n$ matrices over $K$ with entries 1 along the
  diagonal, for some $n$.

  #example[
    The additive group of $K$ is isomorphic to the group ${mat(1, a; 0, 1)}$,
    $a in K$.
  ]
+ $G$ is _reductive_#term-entry("Reductive group") if it has no closed connected
  non-trivial normal unipotent subgroups.

  _Examples._ $upright("GL")(n, K)$, $upright("CSp")(2n, K)$ (the group of
  symplectic similitudes).
+ $G$ is a _torus_ if it is isomorphic to a product of multiplicative groups of
  $K$.

  #example[The group of $n times n$ diagonal matrices over $K$.]

In the famous Chevalley Seminar of 1956–58 @bib:Chevalley1956 the semisimple
groups over $K$ were classified up to isomorphism. The simple ones fall into
families of types $A, B, C, D$ (classical groups) or $G_2, F_4, E_6, E_7, E_8$
(exceptional groups). In the notation we have used above,
$upright("SL")(n, K) = A_(n - 1)(K)$, $upright("SO")(2n + 1, K)$ #source(15)
$= B_(n)(K)$, $upright("SO")(2n, K) = D_(n)(K)$,
$upright("Sp")(2n, K) = C_(n)(K)$. (See @bib:Humphreys1975, §32.)

For the rest of this chapter we assume that $G$ is a connected reductive linear
algebraic group over $K$ and state certain properties of $G$.

#definition[
  A maximal connected solvable subgroup of $G$ is called a Borel subgroup of
  $G$.
  #term-entry("Borel subgroup", target: <def:borel-subgroup>)
] <def:borel-subgroup>

#proposition[
  (See @bib:Humphreys1975, 21.3, 23.1)

  #enum(
    numbering: "(i)",
    [All the maximal tori in $G$ are conjugate in $G$.],
    [All the Borel subgroups of $G$ are conjugate.],
    [If $B$ is a Borel subgroup then $N_(G)(B) = B$.],
  )
] <prop:tori-borel-conjugacy>

The dimension of a maximal torus is called the _rank_ of $G$. $G$ has a maximal
connected normal solvable subgroup called its radical, and the quotient is
semisimple. The rank of the quotient group is called the _semisimple
rank_#term-entry("Semisimple rank") of $G$. Let $T$ be a maximal torus of $G$.
Then $N(T) / T$ is a finite group called the Weyl group of $T$ and denoted by
$W(T)$. It is a finite reflection group. We have the Bruhat
decomposition#term-entry("Bruhat decomposition")
$G = union_(w in W(T)) B dot(w) B$ where $dot(w)$ is a representative for
$w in W$ in $N(T)$, and the double cosets are disjoint. We have $N(T) ∩ B = T$.
(See @bib:Humphreys1975, 28.3.)

A subgroup $P$ of $G$ is called a _parabolic subgroup_ if it contains a Borel
subgroup. A parabolic subgroup $P$ has a _Levi decomposition_, ie.~a semidirect
product decomposition $P = L V$ where $V$ is the maximal connected unipotent
normal subgroup of $P$ and is called the unipotent radical of $P$. $L$ is
reductive and is called a Levi subgroup. It is not unique, #source(16) but any
two Levi subgroups are conjugate. In particular, if $B$ is a Borel subgroup we
have $B = T U$ where $T$ is a maximal torus and $U$ is a maximal unipotent
subgroup of $G$. (See @bib:Humphreys1975, 30.2.)

For any maximal torus $T$ let $X(T) = op("Hom")(T, K^*)$, the group of morphisms
of $T$ into $K^*$ (ie.~characters of $T$) and let $V = X(T) times_Z RR$. Then
$W(T)$ acts on $V$ and this is the natural representation of $W(T)$ as a
reflection group. There is a subset $Phi$ of $X(T)$ which is an abstract root
system (@bib:Humphreys1975, p.~229) in $V$, except that $Phi$ may not generate
$V$ if $G$ is not semisimple. The elements of $Phi$ are called the
_roots_#term-entry("Roots") of $G$ with respect to $T$. We can choose a set of
_simple roots_ $Delta$ in $Phi$ such that every root is either a positive root,
ie.~a linear combination of roots in $Delta$ with positive coefficients, or a
negative root, ie.~a linear combination of roots in $Delta$ with negative
coefficients. Then $Phi = Phi^+ union Phi^-$ where $Phi^+ (Phi^-)$ is the set of
positive (negative) roots. For each $alpha in Phi$ there is a $T$-stable
connected unipotent subgroup $U_alpha$ of $G$ and isomorphisms
$x_alpha: K -> U_alpha$ such that
$t x_(alpha)(u) t^(-1) = x_(alpha)(alpha(t) u)$ ($t in T, u in K$). $G$ is
generated by the _root subgroups_ $U_alpha$ ($alpha in Phi$) and $T$. The
subgroup $U$ generated by the $U_alpha$ ($alpha in Phi^+$) is a maximal
unipotent subgroup. Then $T U$ is a Borel subgroup, and in fact the choice of a
Borel subgroup containing $T$ is equivalent to the choice of a set of simple
roots in $Phi$. The subgroup of $G$ generated by the $U_alpha$
($alpha in Phi^-$) is called the opposite of $U$ and is denoted by $U^-$. For
each $w in W(T)$ let $U_w^- = U ∩ dot(w) U^- dot(w)^(-1)$. Then we have #source(
  17,
) the following refinement of the Bruhat decomposition. #term-entry(
  "Bruhat decomposition",
) Every element $x$ in $G$ can be written uniquely as $x = u dot(w) t u'$ where
$u in U_w^-$, $u' in U$, $t in T$. (See @bib:Humphreys1975, 26.3, 27.3, 28.4.)
<passage:bruhat-refinement>

#remark[
  For an easy treatment of the Bruhat decomposition in the case of
  $upright("SL")_n$ and $upright("Sp")_(2n)$ see @bib:Steinberg1974, p.~73.
]

Finally we mention the Jordan decomposition of elements of $G$. Suppose
$x in upright("GL")(V)$ where $V$ is a finite-dimensional vector space over $K$.
Then we say $x$ is semisimple if $x$ is a diagonalizable automorphism of $V$ and
that $x$ is _unipotent_ if all of its eigenvalues are 1. If $x$ is an arbitrary
element of $upright("GL")(V)$ we have $x = x_s x_u = x_u x_s$ where $x_s$ is
semisimple and $x_u$ is unipotent; $x_s$ and $x_u$ are determined uniquely by
these conditions. Now let $x in G$. Then we have $x = s u = u s$ where, in any
embedding $G -> upright("GL")(V)$, $s$ maps onto a semisimple element and $u$
onto a unipotent element. We call $s$ the semisimple part of $x$ and $u$ the
unipotent part of $x$. (See @bib:Humphreys1975, 15.3.) A torus of $G$ consists
entirely of semisimple elements and a unipotent subgroup consists entirely of
unipotent elements.
