#import "main-defs.typ": *
#import "statements.typ": *

#chapter[Classification of Tori] <ch:classification-of-tori>

#source(18)
In this chapter we will assume that $K = overline(bb(F)_p)$ for some prime $p$.

Let $X$ be an affine variety over $K$. We say $X$ is defined over
$bb(F)_q subset K$, or has an $bb(F)_q$-rational structure, if $X$ can be
defined by a set of polynomials with coefficients in $bb(F)_q$. If $X$ and $Y$
are affine varieties defined over $bb(F)_q$ we can talk of a morphism
$phi: X -> Y$ being defined over $bb(F)_q$; we require a set of polynomials
$psi_1, psi_2, dots, psi_m$ defining $phi$ (see the definition in
Chapter~@ch:algebraic-groups) to be polynomials over $bb(F)_q$.

Suppose $X$ is defined over $bb(F)_q$. Then the affine coordinate ring
$A = K[X]$ has a subring $A_0$ which is an $bb(F)_q$-algebra such that
$A_0 ⊗_(bb(F)_q) K = A$. We have a map $F: A -> A$ called the geometric
Frobenius morphism and defined by $F(a_0 ⊗ lambda) = a_0^q ⊗ lambda$, and a map
$phi: A -> A$ called the arithmetic Frobenius morphism defined by
$phi(a_0 ⊗ lambda) = a_0 ⊗ lambda^q$ ($a_0 in A_0$, $lambda in K$). Then
$F phi = phi F$ is the map $a -> a^q$ of $A$. $F$ is an algebra homomorphism and
is a bijection from $A$ onto $A^q$, and for each $a in A$ there is an $n >= 1$
such that $F^n a = a^(q^n)$. (For the details of this see the proof of
@th:torus-order.) The map $phi$ is a bijection and is a semilinear ring
homomorphism (ie.~$phi(lambda a) = lambda^q phi(a)$ for $lambda in K$,
$a in A$), and for each $a in A$ there is an $n >= 1$ such that
$phi^(n)(a) = a$. Giving an $bb(F)_q$-rational structure on $X$ is equivalent to
defining an $bb(F)_q$-algebra $A_0 subset A$ with $A_0 ⊗ K = A$, and this in
turn is equivalent to giving either a map $F$ or $phi$ with the above
properties. For instance, if #source(19) we are given $phi$, we define $A_0$ as
the set of fixed points of $A$ under $phi$. The fact that for each $a$ we have
$phi^(n)(a) = a$ for some $n$ is used to show that $A_0 ⊗ K = A$, as follows. If
$V$ is the subspace of $A$ generated by ${a, phi a, dots, phi^(n - 1) a}$, it
can be shown that $V^phi subset A_0$ is an $bb(F)_q$-space of dimension equal to
$dim V$, and so $a = sum a_i lambda_i$ with $a_i in A_0$, $lambda_i in K$.

Since $F$ is an algebra homomorphism of $A$ we have a morphism $F: X -> X$ of
which $F: A -> A$ is the comorphism. We call $F$ the Frobenius
morphism#term-entry(
  "Frobenius morphism",
) of $X$ associated with the $bb(F)_q$-rational structure on $X$. In fact, since
we are regarding $X$ as being embedded in $K^n$ for some $n$, we can think of
$F$ as just the restriction to $X$ of the standard Frobenius map of $K^n$ which
takes each "coordinate" $x_i$ to $x_i^q$. In particular, the set $X^F$ of fixed
points of $X$ under $F$ is finite.

#proposition[
  If $g: X -> X$ is an automorphism of $X$ of finite order which commutes with
  $F: X -> X$, then $F g$ is the Frobenius map of $X$ for some
  $bb(F)_q$-rational structure.
] <prop:twisted-frobenius>

#proof[
  From the map $F: X -> X$ we get maps $F: A -> A$ and $phi: A -> A$. We also
  have a map $g: A -> A$ of finite order. Since $(F g)(phi g^(-1))$ is the map
  $a |-> a^q$, it is sufficient to show that $phi g^(-1)$ has the required
  properties to define an $bb(F)_q$-rational structure on $A$. Thus we have to
  show that given $a in A$, $(phi g^(-1))^(n)(a) = a$ for some $n$. But this is
  clear since $phi$ and $g$ commute and $g$ is of finite order.
]

Suppose now we have a linear algebraic group $G$ which is defined over $bb(F)_q$
and let $F: G -> G$ be a Frobenius map of $G$ compatible with the group
structure, ie.~$F$ is a morphism #source(20) of linear algebraic groups. The
group of fixed points $G^F$ is a finite group. The aim of these notes is to
study the characteristic 0 representation theory of finite groups of the form
$G^F$, when $G$ is connected and reductive.

A very important tool in studying the structure of $G^F$ is a theorem of Lang
(see @bib:Borel1969, 16.4). We give below a simple proof of this theorem due to
Steinberg @bib:Steinberg1977. We first state a few definitions and results from
algebraic geometry.

#definition[
  Let $phi: X -> Y$ be a morphism of affine varieties. Then $phi$ is _finite_ if
  $K[X]$ is integral over $phi^*(K[Y])$. $phi$ is dominant if $X$ is irreducible
  and $phi(X)$ is dense in $Y$. (See @bib:Humphreys1975, pp.~30, 31.)
]

#proposition[
  (@bib:Humphreys1975, 4.2.) A finite dominant morphism of affine varieties is
  surjective.
] <prop:finite-dominant-surjective>

#proposition[
  (@bib:Humphreys1975, p.~30.) If $phi: X -> Y$ is a dominant morphism of
  irreducible affine varieties and $e = dim X - dim Y$, then for any $y in Y$
  the dimension of any irreducible component of the fibre $phi^(-1)(y)$ is at
  least $e$.
] <prop:fibre-dimension>

Now consider the algebra $A = K[G]$. Then $G$ acts on $A$ by left translations
$lambda_x$ and right translations $rho_x$ ($x in G$) where
$(lambda_x f)(y) = f(x^(-1) y)$, $(rho_x f)(y) = f(y x)$ ($f in A$,
$x, y in G$). An important fact is that the left or right translates under $G$
of any $f in A$ span a finite-dimensional $K$-subspace of $A$
(@bib:Humphreys1975, 8.6).

We now state Lang's Theorem.

#source(21)
#theorem(title: [Lang])[
  If $G$ is a connected linear algebraic group defined over $bb(F)_q$ and $F$ is
  the Frobenius map, then the map $phi: x -> x (F x)^(-1)$ of $G$ into $G$ is
  surjective.
  #term-entry("Lang's Theorem", target: <th:lang>)
] <th:lang>

#proof[
  (Steinberg) First we note that $phi$ is dominant. For the fibres of $phi$ are
  cosets of $G^F$ and thus finite, ie.~of dimension 0. Hence $phi(G)$ has the
  same dimension as $G$ by applying Proposition~@prop:fibre-dimension to the
  dominant map from $G$ to the closure of $phi(G)$. Since $G$ is irreducible,
  this closure is $G$, so $phi$ is dominant. Thus by
  Proposition~@prop:finite-dominant-surjective it is sufficient to show that
  $phi$ is finite. <passage:lang-finite-fibres>

  Postcomposing $phi$ with inversion gives $L(z) = (F z) z^(-1)$, so it is
  equivalent to prove that $L$ is finite.

  Consider $A = K[G]$. Then $A = A_0 ⊗_(bb(F)_q) K$ where $A_0$ is an
  $bb(F)_q$-algebra and $F(f) = f^q$ for all $f in A_0$. It is then sufficient
  to show that $A_0$ is integral over $(F - 1) A_0$. (Here, as before, we are
  using $F$ also to mean the homomorphism $A -> A$ which is the comorphism of
  $F: G -> G$; we define $((F - 1) f)(z) = f((F z) z^(-1))$.) We note that $A_0$
  is the algebra of regular functions on $G$ defined over $bb(F)_q$.

  Let $f in A_0$. Then if $y, z in G$ we can write
  $f(y z) = sum_i e_(i)(y) f_(i)(z)$, where the $f_i in A_0$ form a (finite)
  $K$-basis for a space of left $G$-translates containing $f$, and the $e_i$
  belong to $A_0$. Then $f_(j)(y z) = sum_i e_(j i)(y) f_(i)(z)$ where the
  $e_(j i)$ belong to $A_0$. Now put $y = (F z) z^(-1)$. Then
  $f_(j)(y z) = f_(j)(F z) = (F f_j)(z)$, whereas
  $sum_i e_(j i)((F z) z^(-1)) f_(i)(z) =
  sum_i ((F - 1) e_(j i) dot f_i)(z)$. This shows that
  $F f_j = sum_i (F - 1) e_(j i) dot f_i$ #source(22) for each $j$. We also have
  $F f_j = f_j^q$, and thus $(F - 1) A_0[{f_j}]$ is finitely generated as an
  $(F - 1) A_0$-module: the monomials in the $f_j$ with each exponent less than
  $q$ generate it. Furthermore each $f_j$ lies in $(F - 1) A_0[{f_j}]$ by
  definition, and hence so does $f$, which is an $bb(F)_q$-linear combination of
  the $f_j$. This shows that $A_0$ is integral over $(F - 1) A_0$ and proves the
  theorem.
  #ed-note[
    The coefficient functions of a translation representation lie in its field
    of definition by the comultiplication of $K[G]$. This is the descent used
    here. For an alternative proof of Lang's theorem through translates of open
    images, see #cite(<Carter1985>, form: "full"), § 1.17.
  ]
]

We now remark that if $F: X -> X$ is a Frobenius morphism of an affine variety
and if $Y$ is a closed subvariety of $X$ then to say that $Y$ is defined over
$bb(F)_q$ is equivalent to $Y$ being $F$-stable. For, $Y$ is defined by an ideal
$I subset A$. Then $F Y = Y$ if and only if $F I = I^q$. Hence if $F Y = Y$ then
$F$ defines a map $A / I -> A^q / I^q$ and this leads to an $bb(F)_q$-rational
structure on $Y$.

We give some examples of Frobenius morphisms of linear algebraic groups and
their groups of fixed points.

#example(numbered: true, series: "frobenius-examples")[
  Let $G = GL(n, K)$, $F: (x_(i j)) -> (x_(i j)^q)$. Then $F$ is called the
  standard Frobenius morphism and $G^F = GL(n, q)$. Similarly from $Sp(2n, K)$,
  $SO(m, K)$ we get the finite groups $Sp(2n, q)$, $SO(m, q)$.
] <exm:standard-frobenius>

#example(numbered: true, series: "frobenius-examples")[
  Let $G = GL(n, K)$, and $tilde(F)$ the "twisted Frobenius" morphism
  $(x_(i j)) -> (x_(j i)^q)^(-1)$. Then $tilde(F)$ is the standard Frobenius
  morphism of Example~@exm:standard-frobenius composed with a "graph
  automorphism" (see @bib:Steinberg1968a, p.~169) and by @prop:twisted-frobenius
  this gives another $bb(F)_q$-rational structure on $G$. We have
  $G^tilde(F) tilde.eq upright("U")(n, q)$.
] <exm:unitary-frobenius>

#example(numbered: true, series: "frobenius-examples")[
  Let $G = Sp(2, K) times Sp(2, K) times dots times Sp(2, K)$ ($n$ copies). Let
  $tilde(F)$ be the morphism of $G$ obtained by composing #source(23) the
  standard Frobenius morphism with the automorphism of order $n$ cyclically
  permuting the factors. Then $G^tilde(F) tilde.eq Sp(2, q^n)$.
] <exm:permuted-frobenius>

_From now on we assume for the rest of these notes, that $G$ is a connected
reductive group defined over $bb(F)_q$ with a Frobenius morphism $F$ compatible
with the group structure._ We define a _torus_ of $G^F$ to be a subgroup of the
form $T^F$ where $T$ is an $F$-stable maximal torus of $G$. We will now describe
the classification of tori in $G^F$ (see @bib:Borel1970, E-20).

Let $H$ be a closed $F$-stable subgroup of $G$.

#definition[
  The elements $x_1, x_2 in H$ are _$F$-conjugate_ in $H$ if there exists an
  element $y in H$ such that $x_2 = y x_1 (F y)^(-1)$.
]

#lemma[
  If two elements $x_1, x_2 in H$ are $F$-conjugate modulo $H^0$ they are
  $F$-conjugate in $H$.
] <lem:f-conjugacy-components>

#proof[
  Let $x_2 = y x_1 (F y)^(-1) t$, $y in H$, $t in H^0$. Then we write
  $x_2 = a (F a)^(-1)$, for some $a in G$. This gives
  $a^(-1) y x_1 (F y)^(-1) (F a) = (F a)^(-1) t^(-1) (F a)$. Since $H^0$ is
  normal in $H$, $(F a)^(-1) t^(-1) (F a) in a^(-1) H^0 a$, and $a^(-1) H^0 a$
  is a connected group. Thus $(F a)^(-1) t^(-1) (F a) =
  (a^(-1) t_1 a) (F a)^(-1) (F t_1)^(-1) (F a)$ for some $t_1 in H^0$, and so
  $y x_1 (F y)^(-1) = t_1 x_2 (F t_1)^(-1)$. Thus $x_1, x_2$ are $F$-conjugate
  in $H$.
]

In the same spirit, we prove

#lemma[
  Let $H$ be connected and suppose $H$ is normal in $N$. Then
  $(N / H)^F tilde.eq N^F / H^F$.
] <lem:fixed-points-quotient>

#proof[
  Let $F(H a) = H a$, then $a (F a)^(-1) in H$. Since $H$ is connected we have
  $a (F a)^(-1) = b (F b)^(-1)$ for some $b in H$. Then #source(24)
  $b^(-1) a in H a$ and is fixed by $F$.
]

#proposition[
  Let $cal(S)$ be an $F$-stable set of subgroups of $G$ such that $G$ acts
  transitively on $cal(S)$ by conjugation.

  #enum(
    numbering: "(i)",
    [There exists $S in cal(S)$ which is fixed by $F$.],
    [Assume $N(S) = N$ is a closed subgroup of $G$. Then there is a bijection
      between the set of $G^F$-conjugacy classes of $F$-fixed elements of
      $cal(S)$, the set of $F$-conjugacy classes of $N$, and the set of
      $F$-conjugacy classes of $N / N^0$.],
  )
] <prop:f-stable-conjugacy>

#proof[
  Let $R in cal(S)$. Then $F(R) = a^(-1) R a$ for some $a in G$. Let
  $a = b (F b)^(-1)$, then $b^(-1) R b$ is $F$-stable. Set $b^(-1) R b = S$.
  Every element of $cal(S)$ can be written as $a^(-1) S a$ for some $a in G$. If
  $a^(-1) S a$ is $F$-stable then $a (F a)^(-1) in N(S) = N$. If $b^(-1) S b$ is
  also $F$-stable and $g^(-1) a^(-1) S a g = b^(-1) S b$ ($g in G^F$), then
  $n = a g b^(-1) in N$ and $a (F a)^(-1) = n b (F b)^(-1) (F n)^(-1)$. Thus we
  have a well-defined map from the set {$G^F$-conjugacy classes of $F$-stable
  elements in $cal(S)$} to the set {$F$-conjugacy classes of $N$}, which is
  injective. It is also surjective, since given $n in N$ we have
  $n = a (F a)^(-1)$ for some $a in G$ and $a^(-1) S a$ maps onto $n$.
  Furthermore, if $n_2 = n(n_1)(F n)^(-1)$ and $n_1 = a (F a)^(-1)$,
  $n_2 = b (F b)^(-1)$ we have $a^(-1) n b = g in G^F$ and
  $g^(-1) a^(-1) S a g = b^(-1) S b$. This proves everything except the last
  part of (ii), which follows from Lemma~@lem:f-conjugacy-components.
]

#corollary[
  #enum(
    numbering: "(i)",
    [There exists a maximal torus $T$ and a Borel subgroup $B$ such that
      $T subset B$ and $T, B$ are fixed by $F$. There is exactly one such pair
      up to $G^F$-conjugacy.],
    [#source(25) Let $T$ be as in (i), and $N(T) / T = W(T)$. Then the
      $G^F$-conjugacy classes of $F$-stable maximal tori of $G$ (and hence the
      conjugacy classes of tori in $G^F$) are in bijection with the
      $F$-conjugacy classes of $W(T)$.],
  )
  #term-entry("Classification of tori", target: <cor:rational-tori>)
] <cor:rational-tori>

#proof[
  (i) Take $cal(S)$ to be the set of Borel subgroups of $G$, and use the fact
  that $N(B) = B$ (see @prop:tori-borel-conjugacy). Thus all $F$-stable Borel
  subgroups of $G$ are $G^F$-conjugate. Then we apply
  Proposition~@prop:f-stable-conjugacy to $B$, and use the fact that
  $N(T) ∩ B = T$. (ii) Take $cal(S)$ to be the set of maximal tori of $G$.
]

From now on we denote by $T_0$ and $B_0$ a pair of subgroups chosen as in
@cor:rational-tori (i). Let $U_0$ be the unipotent radical of $B_0$ so that
$B_0 = T_0 U_0$. The group $W(T_0)$ is called the Weyl group of $G$.
#term-entry("The torus T_0 and the pair (T_0,B_0)", display: [The torus $T_0$
  and the pair $(T_0, B_0)$])

#example[
  If $G = GL(n, K)$ and $F$ is the standard Frobenius morphism we can take $T_0$
  to be the group of diagonal matrices and $B_0$ to be the group of upper
  triangular matrices. Then $W(T_0) tilde.eq S_n$ (symmetric group of degree
  $n$). $F$ is trivial on $W(T_0)$ and the conjugacy classes of tori of $G^F$
  are in bijection with the conjugacy classes of $S_n$, ie.~with partitions of
  $n$.
]

Now suppose $T$ is an $F$-stable maximal torus of $G$. Then we can show that
$T^F$ can be thought of as being obtained from $T_0^F$ by "twisting by an
element of $W$", where $W = W(T_0)$. Let $dot(w)$ be a representative for
$w in W$ in $N(T_0) = N$. Let $T = a^(-1) T_0 a$ for some $a in G$, then
$a (F a)^(-1)$ normalizes $T_0$ #source(26) and thus we can assume that
$a (F a)^(-1) = dot(w)$ for some $w in W$. (Note that $w$ is the element of $W$
which corresponds to $T$ in Corollary~@cor:rational-tori (ii).) We have
$T^F = {a^(-1) t a | t in T_0, (F a)^(-1)(F t)(F a) = a^(-1) t a} =
{a^(-1) t a | t in T_0, dot(w)^(-1) t dot(w) = F t}$. Hence
$a T^F a^(-1) = {t in T_0 | dot(w)^(-1) t dot(w) = F t}$. So $T^F$ is isomorphic
(in fact conjugate in $G$) to the set of fixed points in $T_0$ of a "twisted
Frobenius", ie.~$dot(w) F$.

Next we determine the structure of $N(T)^F / T^F$.

#definition[
  If $w' in W$, let $C'(w') = {w in W | w w' (F w)^(-1) = w'}$.
]

#proposition[
  Suppose $T$ corresponds to $w' in W$. Then $N(T)^F / T^F tilde.eq C'(w')$.
] <prop:rational-tori-weyl-classes>

#proof[
  Suppose $T = a^(-1) T_0 a$ ($a in G$). Then $a (F a)^(-1) = dot(w)' in N$. We
  have $N(T) = a^(-1) N a$ and
  $N(T)^F / T^F = (a^(-1) N a)^F / (a^(-1) T_0 a)^F$. Consider the map
  $(a^(-1) N a)^F -> W$ given by $a^(-1) n a -> w$, where $n in N$ corresponds
  to $w in W$. Then $a^(-1) n a in (a^(-1) N a)^F$ implies that
  $w'^(-1) w w' = F w$, or $w in C'(w')$. Thus $(a^(-1) N a)^F$ maps into
  $C'(w')$, and the kernel is $(a^(-1) T_0 a)^F$. The map is surjective by a
  reasoning similar to that of Lemma~@lem:f-conjugacy-components.
]

We now consider the orders of the tori $T^F$. We first state some facts about
character groups of tori (see @bib:Chevalley1956, Exposé 4).

Recall (Chapter~@ch:algebraic-groups) that if $T$ is a maximal torus $X = X(T)$
denotes the group $Hom(T, K^*)$ of rational characters of $T$. If $T$ is
isomorphic to a product of $ell$ copies of $K^*$ then $X$ is a free abelian
group of rank $ell$ and $Hom_(Z)(X, K^*) tilde.eq T$.

#source(27)
If $A$ is a closed subgroup of $T$ its annihilator $A^0$ in $X$ is a subgroup of
$X$ such that $X / A^0$ has no $p$-torsion, for $p chi in A^0$ ($chi in X$)
implies that $chi(t^p) = 1$ for all $t in A$ and so $chi(t) = 1$ for all
$t in A$. Next, if $B$ is a subgroup of $X$ such that $X / B$ has no $p$-torsion
then $B^(0 0) = B$, where $B^0 = {t in T | chi(t) = 1 "for all" chi in B}$. This
is seen as follows. Let $E = X / B$, then $B^0 = Hom(E, K^*)$ and thus it is
sufficient to show that $∩_(chi in B^0) ker chi = 0$. But this follows from the
fact that if $C$ is a finitely generated abelian group without $p$-torsion,
ie.~$C tilde.eq C' times Z^m$ where $C'$ is a finite abelian group without
$p$-torsion, then $hat(C) = Hom(C, K^*) tilde.eq hat(C') times (K^*)^m$ and
$hat(hat(C)) = Hom(hat(C), K^*) tilde.eq C' times Z^m tilde.eq C$, where the
second dual consists of algebraic characters.

The order of the torus $T^F$ is now given by the following theorem (see
@bib:Borel1970, E-22).

#theorem[
  Let $V = X(T_0) ⊗_Z RR$. Suppose the torus $T$ corresponds to
  $w in W = W(T_0)$ in the sense of @cor:rational-tori (ii). Then
  $|T^F| = |det(w F - 1)|$ where we regard $w, F$ as linear transformations of
  $V$. (Note that there is a natural action of $F$ and $W$ on $X(T_0)$, hence on
  $V$.)
] <th:torus-order>

#proof[
  By Lang's theorem, $F - 1$ is injective on $K[T_0]$ and hence on
  $X = X(T_0) subset K(T_0)^*$. Furthermore, we can show that $X / ((F - 1) X)$
  has no $p$-torsion, as follows. Let $A = K(T_0)$, then $A = A_0 ⊗_(bb(F)_q) K$
  where $A_0$ is an $bb(F)_q$-algebra. Then $F$ takes $a in A_0$ to $a^q$, and
  for each $a in A$ there is an $n$ such that #source(28) $F^n a = a^(q^n)$
  (since $a = sum_i lambda_i a_i$ with $lambda_i in K$, and each $lambda_i$ is
  in a finite extension of $bb(F)_q$). Since $X$ is finitely generated there is
  an $n$ such that $F^n chi = chi^(q^n)$ for all $chi in X$. This says that $F$
  is nilpotent on $X$, mod $p$. Thus $X / ((F - 1) X)$ has finite order prime to
  $p$.

  Now we see by the elementary divisor theorem that
  $|X / ((F - 1) X)| = |det(F - 1)|$. But the annihilator $((F - 1) X)^0$ of
  $(F - 1) X$ in $T_0$ is $T_0^F$, since $(F - 1) chi(t) = 1$ for all $chi in X$
  if and only if $chi(F(t)) = chi(t)$ for all $chi$, ie.~if and only if
  $F t = t$. This shows that $|T_0^F| = |det(F - 1)|$.

  Now consider the torus $T$ which corresponds to $w in W$. Then by the remarks
  made earlier, $T^F$ is isomorphic to the set of fixed points in $T_0$ of
  another Frobenius morphism ie.~$dot(w) F$. By the above arguments we then get
  $|T^F| = |det(w F - 1)|$, as required.
]

#example[
  $G = GL_2$, $F$ the standard Frobenius. We have
  $T_0 = {mat(alpha, 0; 0, beta)}$, $alpha, beta in K^*$. The space $V$ has a
  basis $xi_1, xi_2$ where $xi_1, xi_2 in X$ are defined by
  $xi_1: mat(alpha, 0; 0, beta) -> alpha$,
  $xi_2: mat(alpha, 0; 0, beta) -> beta$. The roots are
  $plus.minus(xi_1 - xi_2)$. The non-trivial element $w$ of $W tilde.eq S_2$
  maps $xi_1$ on $xi_2$ and $xi_2$ on $xi_1$. We have $F: xi_1 -> q xi_1$,
  $xi_2 -> q xi_2$, and $w F: xi_1 -> q xi_2$, $xi_2 -> q xi_1$. Thus
  $|T_0^F| = (q - 1)^2$, and the order of the torus $T^F$ corresponding to $w$
  is $q^2 - 1$. More generally the order of the torus in $GL(n, q)$
  corresponding #source(29) to the partition ${1^(r_1) 2^(r_2) dots k^(r_k)}$ of
  $n$ is $(q - 1)^(r_1) (q^2 - 1)^(r_2) dots (q^k - 1)^(r_k)$.
]

#remark(numbered: true)[
  If the torus $T_0$ is isomorphic over $bb(F)_q$ to a product of copies of
  multiplicative groups, we say $G$ is split over $bb(F)_q$ and that the group
  $G^F$ is an untwisted group.
] <rem:split-group>

We close this chapter with some remarks on the Jordan decomposition and the
Bruhat decomposition in $G^F$.

If $x in G$ then it has a Jordan decomposition as an element of $G$. We see
easily, for example by regarding $x$ as an element of $GL(n, K)$ for some $n$,
that $x$ is semisimple if and only if $x$ is a $p'$-element and that $x$ is
unipotent if and only if $x$ is a $p$-element.

#proposition[
  The finite group $G^F$ has a Bruhat decomposition
  $G^F = union_(w in W^F) B_0^F dot(w) B_0^F$ as a disjoint union of double
  cosets of $B_0^F$. Furthermore every element $x$ of $G^F$ can be written
  uniquely as $x = u dot(w) t u'$ for some $w in W^F$, $u in ((U_0)_w^-)^F$,
  $t in T_0^F$, $u' in U_0^F$.
  #term-entry("Bruhat decomposition", target: <prop:finite-bruhat>)
] <prop:finite-bruhat>

#proof[
  For simplicity we will denote $U_0$ by $U$ in this proposition. If $x in G^F$
  we can write $x$ uniquely as $x = u dot(w) t u'$ for some $w in W$,
  $u in U_w^-$, $t in T_0$, $u' in U$. Hence $x = u_1 n u_2$, where $u_1 = u$,
  $u_2 = u'$ and $n = dot(w) ("mod" T_0)$ and $F x = x = (F u_1)(F n)(F u_2)$.
  Now $U$ is $F$-stable since $B_0$ is $F$-stable, and $U^-$ is $F$-stable since
  $T_0 U^-$ is the unique Borel subgroup opposite to $B_0$ containing $T_0$. So
  we must have $n = F n ("mod" T_0)$, ie.~$F w = w$, ie.~$w in W^F$. Then
  $U_w^-$ is $F$-stable, and we get $u_1 in (U_w^-)^F$, $u_2 in U^F$. By
  Lemma~@lem:fixed-points-quotient every element $w$ #source(30) of $W^F$ has a
  representative $dot(w) in N(T_0)^F$. This shows that
  $G^F = union_(w in W^F) B_0^F dot(w) B_0^F$.
]

#remark[
  The finite simple groups which arise as composition factors of the groups
  $G^F$ are the finite simple groups of Lie type, with the exception of the Ree
  and Suzuki groups. The latter arise as fixed points of an algebraic group
  under an endomorphism some positive power of which is a Frobenius morphism.
  The Lusztig–Deligne theory can be extended to them also, but for simplicity we
  are not considering them here.
]
